const LOCALES = {
  ja: `TARGET_OUTPUT_LOCALE: ja (Japanese). Think and compose the answer directly in natural contemporary Japanese. The source conversation can be Japanese, Chinese, English, or mixed; it is evidence only and MUST NOT change the target output locale. Write every analysis, reason, summary, event title, and suggestion in Japanese. Preserve a person's original name and an exact source excerpt only when a schema field specifically represents a name or evidence quote; do not translate or paraphrase an exact quote. Do not copy the source language into surrounding analysis prose. Match Japanese conversational rhythm, politeness, sentence length, punctuation, and emoji use. Respect Japanese indirectness and conversational timing without assuming that brevity or delayed replies mean rejection. Avoid stiff written Japanese, translated phrasing, and repetitive stock phrases such as 「大丈夫だよ」「無理しないでね」「また落ち着いたら話そう」 unless the conversation genuinely calls for them. Never use the Chinese word 「約会」 in Japanese output; choose natural wording such as 「デート」「会う予定」「デートプラン」 according to context.`,
  "zh-TW": `TARGET_OUTPUT_LOCALE: zh-TW（台灣繁體中文）。請直接以自然的台灣繁體中文思考並撰寫。來源對話可能是日文、中文、英文或混合語言；來源只屬於證據，不得改變目標輸出語言。所有分析、理由、摘要、事件標題與建議都必須使用台灣繁體中文。只有在人名欄位或明確的證據原文欄位中，才保留原始人名或逐字引文；不得翻譯逐字引文，也不得把引文語言延伸到周圍的分析文字。語氣自然、真誠、清楚，依台灣日常溝通習慣調整句型與措辭，不使用中國大陸用語或翻譯腔。可以直接表達感受，但不要逼迫對方表態，也不要把簡短回覆或回覆間隔單獨視為拒絕。`,
  en: `TARGET_OUTPUT_LOCALE: en (English). Think and compose the answer directly in natural contemporary English. The source conversation can be Japanese, Chinese, English, or mixed; it is evidence only and MUST NOT change the target output locale. Write every analysis, reason, summary, event title, and suggestion in English. Preserve a person's original name and an exact source excerpt only when a schema field specifically represents a name or evidence quote; do not translate or paraphrase an exact quote. Do not copy the source language into surrounding analysis prose. Follow natural English-speaking communication patterns rather than Japanese sentence structure. Respect direct communication, consent, and personal boundaries. Do not overread brevity or response delay, and avoid therapy-speak, canned dating advice, and overly polished AI phrasing.`
};

function localeRules(locale) {
  return LOCALES[locale] || LOCALES.ja;
}

module.exports = { localeRules };
