const test=require('node:test'),assert=require('node:assert/strict');
const {createPremiumPipeline,selectedContext,modelCall}=require('../services/premiumDiagnosis');
const {VERSIONS,validateAnalysis,validateFinalCopy}=require('../schemas/premiumUnified');const {fixtures}=require('./premium-unified-fixtures');
const scope={userId:'u1',relationshipId:'r1',sourceSnapshotId:'s1',sourceVersion:'v1',locale:'ja'},messages=[{sender:'partner',text:'また会おう',timestamp:'2026-05-01T12:00:00Z'},{sender:'self',text:'行きたい',timestamp:'2026-05-01T12:01:00Z'}],people={self:'美咲',partner:'レン'},context=selectedContext(messages),f=fixtures(context);
function harness(){const rows=[],calls=[];let failPhase=null;const store={read:async s=>rows.filter(r=>r.scope.userId===s.userId&&r.scope.sourceVersion===s.sourceVersion),begin:async(s,result)=>{rows.unshift({id:String(rows.length),scope:s,result:structuredClone(result)});return rows[0].id},complete:async(id,result)=>{rows.find(r=>r.id===id).result=structuredClone(result)},failed:async()=>{}};const pipeline=createPremiumPipeline({store,callAI:async request=>{calls.push(request);if(request.phase===failPhase)throw new Error('AI_FAILURE');return{value:structuredClone(request.phase==='analysis'?f.analysis:f.copy),metrics:{phase:request.phase,durationMs:1,inputTokens:10,outputTokens:20}}}});return{rows,calls,pipeline,fail:phase=>failPhase=phase}}
test('new full Premium = one shared analysis + one global copy; reopen = zero calls',async()=>{const h=harness(),r=await h.pipeline.generate(scope,messages,people);assert.deepEqual(h.calls.map(c=>c.phase),['analysis','finalCopy']);assert.equal(r.generation.aiCalls,2);assert.equal(h.rows.length,1);assert.deepEqual(Object.keys(r.globalFinalCopy),['type','feelings','future']);assert.equal(h.calls[1].input.unifiedAnalysis,r.unifiedAnalysis);assert.deepEqual(h.calls[0].input.selectedContext,h.calls[1].input.selectedContext);assert.deepEqual(h.calls[1].input.sharedFactPool,r.unifiedAnalysis.facts);const again=await h.pipeline.generate(scope,[],people);assert.equal(again.generation.aiCalls,0);assert.equal(again.generation.cached,true);assert.equal(h.calls.length,2)});
test('valid unified analysis with stale copy uses just one global call and preserves legacy row',async()=>{const h=harness();await h.pipeline.generate(scope,messages,people);h.rows[0].result.finalCopyPromptVersion='stale';h.calls.length=0;const r=await h.pipeline.generate(scope,messages,people);assert.deepEqual(h.calls.map(c=>c.phase),['finalCopy']);assert.equal(r.generation.analysisReused,true);assert.equal(h.rows.length,2);assert.equal(h.rows[1].result.finalCopyPromptVersion,'stale')});
test('old per-theme analysis is never migrated silently',async()=>{const h=harness();h.rows.push({scope,result:{analysisSchemaVersion:'diagnosis-theme-analysis-v1',analysis:{stages:[]},generation:{source:'real-ai'}}});await h.pipeline.generate(scope,messages,people);assert.equal(h.calls.length,2);assert.equal(h.rows.length,2)});
test('stale analysis prompt forces exactly 1+1 and scopes source/user caches',async()=>{const h=harness();await h.pipeline.generate(scope,messages,people);h.rows[0].result.analysisPromptVersion='stale';h.calls.length=0;await h.pipeline.generate(scope,messages,people);assert.equal(h.calls.length,2);await h.pipeline.generate({...scope,userId:'u2'},messages,people);assert.equal(h.calls.length,4)});
test('simultaneous theme requests share the same 1+1 runtime',async()=>{const h=harness();const results=await Promise.all([1,2,3].map(()=>h.pipeline.generate(scope,messages,people)));assert.equal(h.calls.length,2);assert.equal(h.rows.length,1);assert.equal(results[0],results[2])});
test('analysis failure stops before final copy; no fake or legacy result',async()=>{const h=harness();h.fail('analysis');await assert.rejects(h.pipeline.generate(scope,messages,people),/AI_FAILURE/);assert.equal(h.calls.length,1);assert.equal(h.rows.length,0)});
test('final failure preserves unified analysis; explicit retry costs only one call',async()=>{const h=harness();h.fail('finalCopy');await assert.rejects(h.pipeline.generate(scope,messages,people),/AI_FAILURE/);assert.equal(h.calls.length,2);assert.equal(h.rows[0].result.globalFinalCopy,null);h.fail(null);h.calls.length=0;await h.pipeline.generate(scope,messages,people);assert.deepEqual(h.calls.map(c=>c.phase),['finalCopy'])});
test('deterministic schema rejects empty fields, missing themes, wrong card count and invented IDs',()=>{for(const mutate of [c=>delete c.future,c=>c.type.headline='',c=>c.feelings.insights.pop(),c=>c.future.insights[0].supportFactIds=['DOES_NOT_EXIST']]){const c=structuredClone(f.copy);mutate(c);assert.throws(()=>validateFinalCopy(c,f.analysis))}const a=structuredClone(f.analysis);a.facts[0].sourceMessageIds=['invented'];assert.throws(()=>validateAnalysis(a,context),/MESSAGE_ID/)});
test('deterministic overlap rejects repeated titles, excessive phrases and one primary fact across all themes',()=>{for(const mutate of [c=>c.future.insights[0].title=c.type.insights[0].title,c=>c.future.narrative=c.type.narrative,c=>{for(const t of ['type','feelings','future'])c[t].insights[0].supportFactIds=['F01']}]){const c=structuredClone(f.copy);mutate(c);assert.throws(()=>validateFinalCopy(c,f.analysis),/DUPLICATE|OVERLAP|DOMINATES/)}});
test('HTTP failure has one transport attempt, no retry/repair model call',async()=>{const prior=global.fetch,key=process.env.OPENAI_API_KEY;let count=0;process.env.OPENAI_API_KEY='test';global.fetch=async()=>{count++;return{ok:false,status:500}};try{await assert.rejects(modelCall({phase:'analysis',prompt:'test',input:{},schema:{}}));assert.equal(count,1)}finally{global.fetch=prior;if(key===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=key}});
