const VERSIONS=Object.freeze({analysisSchemaVersion:'premium-unified-analysis-v1',analysisPromptVersion:'premium-unified-analysis-prompt-v1',finalCopySchemaVersion:'premium-global-final-copy-v1',finalCopyPromptVersion:'premium-global-final-copy-prompt-v1'});
const string={type:'string',minLength:1},list=(items,min=1,max=20)=>({type:'array',items,minItems:min,maxItems:max}),object=properties=>({type:'object',additionalProperties:false,required:Object.keys(properties),properties}),choice=values=>({type:'string',enum:values});
const themes=['type','feelings','future'];
const refs=list(string,1,6),claim=object({text:string,supportFactIds:refs});
const analysisBody=object({relationshipState:string,trajectory:string,confidence:choice(['low','medium','high']),evidenceQuality:object({summary:string,limitations:list(string,0,6)}),facts:list(object({id:{type:'string',pattern:'^F[0-9]{2,3}$'},category:choice(['initiative','reciprocity','emotional_expression','reconnection','cooling','planning','conflict','repair','timing','affection','avoidance','consistency','relationship_definition','trajectory']),statement:string,kind:choice(['observation','grounded_interpretation']),strength:choice(['low','medium','high']),recency:choice(['baseline','recent','change_over_time']),sourceMessageIds:list(string,1,8),relevantThemes:list(choice(themes),1,3)}),6,18),typeAnalysis:object({relationshipPattern:claim,sharedRhythm:claim,distinctiveDynamic:claim,tension:claim}),feelingsAnalysis:object({focalPerson:string,emotionalPosition:claim,investment:claim,changeOverTime:claim,unresolvedEmotion:claim}),futureAnalysis:object({currentTrajectory:claim,likelyNextDevelopment:claim,branchPoint:claim,confirmingSignal:claim,stagnationSignal:claim})});
const theme=object({headline:{type:'string',minLength:8,maxLength:80},narrative:{type:'string',minLength:60,maxLength:240},insights:list(object({title:{type:'string',minLength:6,maxLength:60},body:{type:'string',minLength:35,maxLength:180},supportFactIds:refs}),2,2)});
const finalBody=object({type:theme,feelings:theme,future:theme});
const analysisSchema={name:'renai_premium_unified_analysis_v1',strict:true,schema:analysisBody},finalCopySchema={name:'renai_premium_global_final_copy_v1',strict:true,schema:finalBody};
function validateShape(value,schema,path='root'){
 const fail=()=>{throw new Error('PREMIUM_SCHEMA_INVALID:'+path)};
 if(schema.type==='object'){if(!value||typeof value!=='object'||Array.isArray(value))fail();if(Object.keys(value).some(k=>!Object.hasOwn(schema.properties,k)))fail();for(const k of schema.required)validateShape(value[k],schema.properties[k],path+'.'+k)}
 else if(schema.type==='array'){if(!Array.isArray(value)||value.length<schema.minItems||value.length>schema.maxItems)fail();value.forEach((v,i)=>validateShape(v,schema.items,path+'.'+i))}
 else if(schema.type==='string'){if(typeof value!=='string'||!value.trim()||value.length<(schema.minLength||1)||value.length>(schema.maxLength||Infinity)||schema.enum&&!schema.enum.includes(value)||schema.pattern&&!new RegExp(schema.pattern).test(value))fail()}
}
function validateReferences(value,ids){if(Array.isArray(value))value.forEach(v=>validateReferences(v,ids));else if(value&&typeof value==='object'){for(const[k,v]of Object.entries(value)){if(k==='supportFactIds'){if(new Set(v).size!==v.length||v.some(id=>!ids.has(id)))throw new Error('PREMIUM_UNKNOWN_OR_DUPLICATE_FACT_ID')}else validateReferences(v,ids)}}}
function validateAnalysis(value,context){validateShape(value,analysisBody);const ids=new Set(value.facts.map(f=>f.id));if(ids.size!==value.facts.length)throw new Error('PREMIUM_DUPLICATE_FACT_ID');validateReferences(value,ids);if(context){const messages=new Set([...context.baseline,...context.recent].map(m=>m.id));if(value.facts.some(f=>f.sourceMessageIds.some(id=>!messages.has(id))))throw new Error('PREMIUM_UNKNOWN_MESSAGE_ID')}return value}
const normalize=s=>s.normalize('NFKC').toLowerCase().replace(/[\p{P}\p{S}\s]/gu,'');
function overlapChecks(copy){const titles=themes.flatMap(t=>copy[t].insights.map(i=>normalize(i.title)));if(new Set(titles).size!==6)throw new Error('PREMIUM_DUPLICATE_INSIGHT_TITLE');const primary=themes.map(t=>copy[t].insights.map(i=>i.supportFactIds[0]));if(primary[0].some(id=>primary[1].includes(id)&&primary[2].includes(id)))throw new Error('PREMIUM_PRIMARY_FACT_DOMINATES_ALL_THEMES');const texts=themes.flatMap(t=>[copy[t].narrative,...copy[t].insights.map(i=>i.body)]).map(normalize);for(let i=0;i<texts.length;i++)for(let j=i+1;j<texts.length;j++){const a=texts[i],b=texts[j],grams=new Set(Array.from({length:Math.max(0,a.length-17)},(_,n)=>a.slice(n,n+18)));const hits=Array.from({length:Math.max(0,b.length-17)},(_,n)=>b.slice(n,n+18)).filter(g=>grams.has(g)).length;if(hits>12&&hits/Math.max(1,Math.min(a.length,b.length)-17)>.45)throw new Error('PREMIUM_EXCESSIVE_PHRASE_OVERLAP')}return{identicalTitles:false,excessiveRepeatedPhrases:false,samePrimaryFactAcrossAllThemes:false}}
function validateFinalCopy(value,analysis){validateShape(value,finalBody);validateAnalysis(analysis);validateReferences(value,new Set(analysis.facts.map(f=>f.id)));overlapChecks(value);for(const t of themes){if(value[t].insights.some(i=>/[?？]/u.test(i.title)))throw new Error('PREMIUM_QUESTION_TITLE');const prose=[value[t].headline,value[t].narrative,...value[t].insights.flatMap(i=>[i.title,i.body])].join('\n');if(/ユーザー|相手側|\b(?:user|other person|SELF|PARTNER)\b/iu.test(prose))throw new Error('PREMIUM_SYSTEM_ACTOR_LANGUAGE')}return value}
module.exports={VERSIONS,analysisSchema,finalCopySchema,validateAnalysis,validateFinalCopy,overlapChecks,themes};
